Repository odpf/guardian, pull requests merged in 2022-01, with the labels that each got.

#97 fix(appeal): immediately activate appeal if all the approvals passed/approved during the creation
  appeal/service.go
  appeal/service_test.go
  approval/service.go
  domain/appeal.go
Labels: bug

#98 feat: add cli config manager
  .github/workflows/release.yaml
  .github/workflows/test.yaml
  .golangci.yaml
  app/cli.go
  app/config.go
  appeal/repository_test.go
  appeal/service.go
  cmd/appeal.go
  cmd/client.go
  cmd/config.go
  cmd/migrate.go
  cmd/root.go
  go.mod
  go.sum
  main.go
  policy/service_test.go
  provider/bigquery/bigquery.go
  provider/bigquery/provider.go
  provider/gcloudiam/client.go
  provider/gcloudiam/provider_test.go
  provider/grafana/client.go
  provider/grafana/provider.go
  provider/grafana/provider_test.go
  provider/metabase/client.go
  provider/metabase/provider_test.go
  provider/service_test.go
  provider/tableau/client.go
  provider/tableau/config.go
  provider/tableau/provider.go
  provider/tableau/provider_test.go
Labels: enhancement

#116 fix: fix bugs
  cmd/resource.go
  core/policy/service_test.go
  domain/policy.go
Labels: bug

#112 feat: policy view command support version flag
  cmd/policy.go
Labels: cli

#118 fix(appeal): remove fatal logging in revoke expired access job handler
  core/appeal/job_handler.go
Labels: bug

#117 feat: cli-ux-enhancements
  cmd/appeal.go
  cmd/policy.go
  cmd/provider.go
  cmd/resource.go
  go.mod
  go.sum
  main.go
  spec/policy.yml
  spec/provider.yml
Labels: cli

#113 feat: update missing cli features
  cmd/appeal.go
  cmd/policy.go
  cmd/provider.go
  cmd/resource.go
Labels: cli

#114 docs: update docs
  docs/docs/guides/managing-appeals.md
  docs/docs/guides/managing-appeals.mdx
  docs/docs/guides/managing-policies.md
  docs/docs/guides/managing-policies.mdx
  docs/docs/guides/managing-providers.md
  docs/docs/guides/managing-providers.mdx
  docs/docs/guides/managing-resources.md
  docs/docs/guides/managing-resources.mdx
  docs/docs/providers/bigquery.md
  docs/docs/providers/gcloud_iam.md
  docs/docs/reference/appeal.md
  docs/docs/reference/overview.md
  docs/docs/reference/policy-config.md
  docs/docs/reference/policy.md
  docs/docs/reference/provider.md
  docs/docs/reference/resource.md
  docs/sidebars.js
  docs/yarn.lock
Labels: documentation
